version: '3.8'

services:
  redis:
    image: bitnami/redis:6.2.6
    platform: linux/amd64
    container_name: redis-single
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=password123
    networks:
      - backend-network
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_db
    ports:
      - '5432:5432'
    networks:
      - backend-network
networks:
  backend-network: