CREATE SCHEMA IF NOT EXISTS schema_sit;

CREATE TABLE IF NOT EXISTS users (
	id serial PRIMARY KEY,
	username VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	email VARCHAR (255) UNIQUE NOT NULL,
    enabled BOOLEAN NOT NULL,
	created_date TIMESTAMP NOT NULL,
    last_login TIMESTAMP
);